// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plantify.Data;

namespace Plantify.Migrations
{
    [DbContext(typeof(PlantifyContext))]
    [Migration("20201205110532_InitialCreate4")]
    partial class InitialCreate4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Plantify.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ProductCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("ProductID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Plantify.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Plantify.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("Plantify.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Plantify.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Category = "Grande",
                            Description = "The Mega Grande Ecosystem is an elegant glass flask filled with a self-sufficient plants that require no watering or up-keep.",
                            ImageUrl = "mega-grande-ecosystem.png",
                            Price = 1390.95m,
                            ProductName = "Mega Grande Ecosystem",
                            Stock = 15
                        },
                        new
                        {
                            ProductID = 2,
                            Category = "Ecospheres",
                            Description = "Our bestselling Ecosphere of 2020! The airtight spherical flask is made from recycled glass and is sealed with a cork lid. This popular globe shape is a unique design and is limited edition. It is filled with three stunning tropical plants, including a tree, in a green moss base, all of which have been specially selected by our botanical experts making the perfect bottle garden. Please note plants may vary. It’s the ideal gift for someone who loves the idea of keeping real plants inside their home or office space, but doesn’t have the time to keep them well-maintained. The whole ecosystem is completely self - sufficient, perfect for those that love the addition of greenery in the home but do not have the spare time to maintain the plants. Not only can you enhance any indoor space with a splash of colour, the air-purifying houseplants can rid it of harmful toxins too. This item is available as a fully assembed item or a DIY ecosystem.In our DIY version, all the plants, moss and soil are individually wrapped for the receipient to create their own ecosystem, perfect for the more creative and green fingered! Personalisation and fairy lights are available with the product, making the ideal gift for a loved one.",
                            ImageUrl = "secret-garden-ecosystem.png",
                            Price = 1240.95m,
                            ProductName = "Secret Garden Ecosystem",
                            Stock = 3
                        },
                        new
                        {
                            ProductID = 3,
                            Category = "Ecospheres",
                            Description = "The Limited Edition Biome Ecosystem is an elegant flask made from recycled glass. It is sealed with a cork lid containing self-sufficient plants that require no upkeep or watering. This indoor garden is a great gift for those who like the look of real plants but lack the time or desire to spend on maintenance. The sealed flask allows the process of photosynthesis, keeping the contents fresh and healthy. The self-sustaining plants are chosen by botanical experts. This product comes fully assembled, a DIY option is also available.",
                            ImageUrl = "biome-ecosystem.png",
                            Price = 990.95m,
                            ProductName = "Biome Ecosystem",
                            Stock = 7
                        },
                        new
                        {
                            ProductID = 4,
                            Category = "Ecospheres",
                            Description = "If you’re looking for the ideal little gift for any plant lover, our Arabica Ecojar can provide a unique display of eye-catching greenery just for them. The self-sufficient ecojar houses a stunning, hand-picked coffea arabica plant, which requires absolutely no maintenance whatsoever. This stress - free, air - purifying houseplant plant is perfect for those with a little green - fingered passion, but who simply don’t have the time to constantly maintain it with a busy schedule.Plus, it makes a great gift if they happen to love coffee too.It sits on a beautiful moss base, within the sealed airtight kilner jar. And if you wanted to give it that extra special touch, you can even add some fairy lights to it, to transform this piece into an even more eye-catching statement for the home, office or retail space.Plant care instructions are included, but the beauty of this ecojar is that it is completely self-sufficient, and works wonders for your wellbeing.This product is now available as a DIY kit!",
                            ImageUrl = "aranica-ecojar.png",
                            Price = 590.95m,
                            ProductName = "Aranica Ecojar",
                            Stock = 23
                        },
                        new
                        {
                            ProductID = 5,
                            Category = "Ecospheres",
                            Description = "An elegant ecosystem can be the ideal gift for any plant-lover, and with our Duo Baby & Petite Ecosystem set, you can get double the green-fingered goodness. Both of the airtight flasks are made from recycled glass with a cork stopper, and contain a selection of three tropical plants and French natural ball moss. The plants are seasonal and hand-picked by our botanical experts. The self - sufficient ecosystems require no care, making it the perfect present for those with an eye for interiors.A bed of hydro grains stores excess water that is released when the plants need it, keeping the contents hydrated but without any need to water them. Not only can you enhance any indoor space with these beautiful tropical plants, but their air - purifying qualities can rid it of any harmful toxins too.",
                            ImageUrl = "duo-small-ecosystem.png",
                            Price = 1640.95m,
                            ProductName = "Duo Small Ecosystem",
                            Stock = 11
                        },
                        new
                        {
                            ProductID = 6,
                            Category = "Grande",
                            Description = "Choose the perfect green-fingered gift with our ultimate ecosystem set for plant-lovers. The Grande & Mega Grande Ecosystem Duo set includes two elegant glass flasks made from recycled glass. They are filled with self-sufficient hand-picked plants that require no upkeep or watering. Acting as a maintenance - free indoor garden, this set makes a great gift for those who like the look of real plants but lack the time or desire to constantly maintenance them, alongside a busy schedule. Plus, the sealed flask allows the process of photosynthesis to take place, keeping the contents fresh and healthy.The seasonal tropical plants are specially selected by our botanical experts. This item arrives fully assembed, we also offer a DIY set for the more creative!",
                            ImageUrl = "duo-grande-ecosystem.png",
                            Price = 2140.95m,
                            ProductName = "Duo Grande Ecosystem",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 7,
                            Category = "Ecospheres",
                            Description = "The airtight flask is made from recycled glass and is sealed with a cork lid. This elegent teardrop shape is a unique design and is limited edition. It is filled with three stunning tropical plants on a green moss base, all of which have been specially selected by our botanical experts making the perfect bottle garden. Please note plants may vary. It’s the ideal gift for someone who loves the idea of keeping real plants inside their home or office space, but doesn’t have the time to keep them well-maintained. The whole ecosystem is completely self - sufficient, perfect for those that love the addition of greenery in the home but do not have the spare time to maintain the plants. Not only can you enhance any indoor space with a splash of colour, the air-purifying houseplants can rid it of harmful toxins too. This item is available as a fully assembed item or a DIY ecosystem.In our DIY version, all the plants, moss and soil are individually wrapped for the receipient to create their own ecosystem, perfect for the more creative and green fingered! Personalisation and fairy lights are available with the product, making the ideal gift for a loved one.",
                            ImageUrl = "teardrop-ecosystem.png",
                            Price = 1240.95m,
                            ProductName = "Teardrop Ecosystem",
                            Stock = 4
                        },
                        new
                        {
                            ProductID = 8,
                            Category = "Ecospheres",
                            Description = "The airtight flask is made from recycled glass and is sealed with a cork lid. It is filled with three stunning tropical plants on a natural French ball moss base, all of which have been specially selected by our botanical experts. It’s the ideal gift for someone who loves the idea of keeping real plants inside their home or office space, but doesn’t have the time to keep them well-maintained. The whole ecosystem is completely self - sufficient, perfect for those that love the addition of greenery in the home but do not have the spare time to maintain the plants. Not only can you enhance any indoor space with a splash of colour, the air-purifying houseplants can rid it of harmful toxins too. This item arrives fully assembled, we also have a DIY option available and our Duo sets are the perfect gift!",
                            ImageUrl = "petite-ecosystem.png",
                            Price = 890.95m,
                            ProductName = "Petite Ecosystem",
                            Stock = 3
                        },
                        new
                        {
                            ProductID = 9,
                            Category = "Grande",
                            Description = "Our DIY Grande Mossarium is one of our exciting recently launched products! The product arrives as a DIY kit with vibrant green ball moss, gravel, decorative pebbles, compost and charcoal, complete with an elegant large glass sphere vase with lid. The mossarium makes a unique and stirking focal point in any interior and does not require any watering or upkeep! This indoor botanical product is a great gift for those who like the look of real plants but lack the time or desire to spend on maintenance.Our on trend Mossarium is easy to assemble, layering the gravel, compost, moss balls and decoartive stones.This mossarium makes the perfect gift and can be personalised and fairy lights can be added for that extra wow factor!",
                            ImageUrl = "grande-mosarium.png",
                            Price = 1290.95m,
                            ProductName = "Grande Mosarium",
                            Stock = 0
                        });
                });

            modelBuilder.Entity("Plantify.Models.Category", b =>
                {
                    b.HasOne("Plantify.Models.Product", "Product")
                        .WithMany("CategoryNames")
                        .HasForeignKey("ProductID");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Plantify.Models.Invoice", b =>
                {
                    b.HasOne("Plantify.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Plantify.Models.OrderItem", b =>
                {
                    b.HasOne("Plantify.Models.Invoice", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plantify.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Plantify.Models.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Plantify.Models.Invoice", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Plantify.Models.Product", b =>
                {
                    b.Navigation("CategoryNames");
                });
#pragma warning restore 612, 618
        }
    }
}
